/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_universe_free: (a: number, b: number) => void;
export const allocate_bytes: (a: number) => number;
export const apply_blur: (a: number, b: number, c: any, d: number, e: number) => void;
export const apply_grayscale: (a: number, b: number, c: any) => void;
export const apply_invert: (a: number, b: number, c: any) => void;
export const benchmark_loop: (a: number) => number;
export const fibonacci: (a: number) => bigint;
export const generate_primes: (a: number) => [number, number];
export const get_allocation_count: () => number;
export const get_total_allocated_bytes: () => number;
export const get_version_info: () => [number, number];
export const get_wasm_page_size: () => number;
export const init: () => void;
export const is_prime: (a: number) => number;
export const mandelbrot_set: (a: number, b: number, c: number) => [number, number];
export const matrix_multiply: (a: number) => [number, number];
export const probe_environment: () => [number, number];
export const quicksort: (a: number, b: number, c: any) => void;
export const reset_allocation_stats: () => void;
export const sha256: (a: number, b: number) => [number, number];
export const stress_test_compute: (a: number) => number;
export const test_stack_depth: (a: number) => number;
export const universe_alive_cells: (a: number) => number;
export const universe_cells: (a: number) => number;
export const universe_clear: (a: number) => void;
export const universe_height: (a: number) => number;
export const universe_new: (a: number, b: number) => number;
export const universe_randomize: (a: number) => void;
export const universe_set_cell: (a: number, b: number, c: number, d: number) => void;
export const universe_tick: (a: number) => void;
export const universe_width: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
